# Generated by Django 3.0.8 on 2020-07-23 13:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentcreditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcreditcard',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment_credit_card', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentcreditcard',
            name='security_code',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
